Unit tests modules/accounts
RiseVision/rise-node pull request #16
Opened 2017-10-09 09:45 UTC by roman-bystrimovich

2017-10-11 09:41 UTC, nerdvibe requested changes
I believe I've already reviewed this PR, but here is my review :)

Nice PR, I've left some comments.

Also, if I'm not wrong the `setAccountAndGet` and `isLoaded` are not covered in the test. Is this on purpose?

2017-10-11 09:41 UTC, nerdvibe commented on tests/unit/modules/accounts.spec.js
> +            expect(callback.called).to.be.true;
Isn't this redundant?

2017-10-11 09:41 UTC, nerdvibe commented on tests/unit/modules/accounts.spec.js
> +        it("public.getAccounts", function() {
I was a bit confused, shouldn't this be in a separate describe?

2017-10-11 09:41 UTC, xunga commented on tests/unit/modules/accounts.spec.js
> +            expect(scope.schema.validate.calledOnce).to.be.
broken indentation...

2017-10-12 10:05 UTC, roman-bystrimovich commented
@xunga fixed

2017-10-12 10:09 UTC, nerdvibe approved these changes

2017-10-12 10:10 UTC, xunga commented
@roman-bystrimovich all righty! Then for me it's a 👍

2017-10-20 17:23 UTC, vekexasia commented
@roman-bystrimovich can you please commit something into this so that travis can check against developmnet and code coverage?

2017-10-20 18:26 UTC, merged