Removed additionalProperties from Block.schema
RiseVision/rise-node pull request #52
Opened 2017-10-28 10:25 UTC by jarenal

To remove additionalProperties from Block.schema requested by @vekexasia 

Ready for to review & to merge

2017-10-28 10:31 UTC, jarenal commented
I have to update logic/block unit test because after remove additionalProperties from Block.schema the test fail.

2017-10-28 10:43 UTC, jarenal commented
Ready for to review & to merge

2017-10-31 18:44 UTC, vekexasia requested changes
Please fix the associated test :)

2017-10-31 18:45 UTC, vekexasia approved these changes

2017-10-31 18:45 UTC, merged